<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>BitPlusTool</AssemblyName>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <Version Condition="'$(Version)'==''">1.0.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\template.xml" />
    <EmbeddedResource Include="Resources\codedata.csv" />
    <EmbeddedResource Include="Resources\motordata.csv" />
    <Resource Include="Resources\AppIcon.ico" />
  </ItemGroup>

</Project>
