<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BitPlusTool">
      <HintPath>C:\Users\tlangfe\source\BitPlusTool\bin\Release\net10.0-windows\win-x64\BitPlusTool.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
